fix php type checks due to undue quote "
Fix many PHP errors while running make test:

Fatal error: Uncaught TypeError: Argument 1 passed to Pkcs11\Module::C_GetSessionInfo() must be an instance of "Pkcs11\\Session", instance of Pkcs11\Session given in php-pkcs11/tests/0260-oasis_Session.php:13

Using gcc -E, we get the following expansion of the Macros:

static const zend_internal_arg_info arginfo_C_OpenSession[] = { { (const char*)(zend_uintptr_t)(5), 0, 0, 0 },
    { "slotID", (((4) << 2L) | ((0) ? 0x1L : 0x0L)), 0, 0 },
    { "flags", (((4) << 2L) | ((0) ? 0x1L : 0x0L)), 0, 0 },
    { "pApplication", (((6) << 2L) | ((1) ? 0x1L : 0x0L)), 0, 0 },
    { "notify", (((17) << 2L) | ((1) ? 0x1L : 0x0L)), 0, 0 },
    { "hSession", ((zend_type) "?" "\"Pkcs11\\\\Session\""), 1, 0 },
};

It is clear that the quote " should not be set.

Thanks to this fix, the 14 tests are "Success".